### PR TITLE
Update README.md

### LINKED ISSUE #136: Inclusion in F-Droid
Hi,

Since this app is LGPLv3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, that do not use Google Play nor anything else, except F-Droid.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small and useless PR adds two buttons to get your app on F-Droid and Google Play 👍 
(Do not forget to tag your releases to have automatic updates on F-Droid)

close #136

### CODE REVIEW

**Comment by joaomneto** [comment]
Hey @Poussinou thanks!

Just a question please:

I'm confused as to how FDroid will have new versions available. I have to manually assemble the apk and upload it? Or FDroid polls Github for new tags with the good format and assembles it itself? Did you assemble the v60 yourself?

Kind regards!

**Comment by Poussinou** [comment]
Once you're ready to release a new version, just tag it, F-Droid will do the rest, you have nothing else to do by your side

(As you can see [here](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/pt.joaomneto.titancompanion.txt), `Auto Update Mode` has argument `Version %v` and check mode is set on tags, it means F-Droid will look for a new tag (=new version) regularly, and will build the new version from source automatically. Then, it will be available for everyone via the Android client, and also on the F-Droid website).

I didn't built v60 myself, but Rudloff did it (faster than me xD ) via the F-Droid server tools. Since it succeeded, your app is now available for everyone via F-Droid 👍 

Is my answer clear enough? Otherwise, ask ;)

**Comment by joaomneto** [comment]
Perfect @Poussinou. I already integrated the automated tagging with the good format in my CD pipeline in CircleCI. The v60 was produced by it just before deploying to play store so everything is automated and in the perfect format. Thanks for the update to the README. I'll merge!

**Comment by Poussinou** [comment]
Perfect, thanks for F-Droid 👍

**Pull request merged**
